Repository priyam-03/Recruitify, pull requests merged in 2024-10, with the labels that each got.

#25 Beautified CSS for FormById Component - Modern, Responsive, and Scrollable
  backend/uploads/2024-10-17T11-56-12.905Z-background.png
  backend/uploads/2024-10-17T11-56-21.197Z-background.png
  frontend/src/Jobs/FormById.js
  frontend/src/styles/formById.module.css
Labels: hacktoberfest-accepted

#33 Recruitify v7.2
  frontend/src/Jobs/CreateJobs.js
  frontend/src/styles/createJobForms.css
Labels: hacktoberfest-accepted

#39 Recruitifyv1
  backend/socketHandlers/pubSub.js
  frontend/src/Jobs/FormById.js
  frontend/src/Jobs/JobForm.js
  frontend/src/realtimeCommunication/socketConnection.js
  frontend/src/shared/components/homePage.js
  frontend/src/styles/jobForms.css
Labels: hacktoberfest-accepted

#40 updated Job Form onclick functionalities
  frontend/src/Jobs/JobForm.js
  frontend/src/shared/components/homePage.js
Labels: hacktoberfest-accepted

#47 recruiter profile default pic added and section stablilised and beaut…
  frontend/public/ppic.jpg
  frontend/src/Jobs/FormById.js
  frontend/src/styles/formById.module.css
Labels: enhancement, hacktoberfest, frontend, hacktoberfest-accepted, advanced

#49 updated jobs-applied-by-me ui
  frontend/src/screens/JobsAppliedByMe.js
Labels: hacktoberfest, hacktoberfest-accepted, advanced

#51 Createpost
  frontend/src/User/CreatePost.css
  frontend/src/User/createPost.js
  frontend/src/shared/components/CreatepostTextSection.js
  frontend/src/styles/TextSection.css
Labels: enhancement, hacktoberfest, frontend, hacktoberfest-accepted, advanced

#48 Fix:mordernizing login and signup page
  frontend/src/screens/LoginScreen.js
  frontend/src/screens/RegisterScreen.js
  frontend/src/styles/Login.module.css
  frontend/src/styles/login.css
  frontend/src/styles/register.css
  frontend/src/styles/register.module.css
Labels: enhancement, frontend, hacktoberfest-accepted

#56 Home-dashboard
  frontend/src/screens/HomeScreen.js
  frontend/src/shared/components/dashboard.js
  frontend/src/shared/components/homePage.js
  frontend/src/styles/dashboard.module.css
  frontend/src/styles/homePage.module.css
Labels: hacktoberfest, hacktoberfest-accepted

#61 Homestyle
  frontend/src/shared/components/homePage.js
  frontend/src/styles/HomeScreen.css
  frontend/src/styles/homePage.module.css
Labels: enhancement, hacktoberfest, frontend, hacktoberfest-accepted

#52 fixed user-avatar onclick functionalities
  frontend/src/App.js
  frontend/src/screens/ProfileScreen.js
  frontend/src/shared/components/Avatar.js
  frontend/src/shared/components/Header.js
  frontend/src/shared/components/UserPopover.js
  frontend/src/shared/components/dashboard.js
Labels: enhancement, hacktoberfest, frontend, hacktoberfest-accepted, advanced

#63 Login and signup UI
  frontend/src/screens/LoginScreen.js
  frontend/src/screens/RegisterScreen.js
  frontend/src/styles/Login.module.css
  frontend/src/styles/register.module.css
Labels: enhancement, hacktoberfest, frontend, hacktoberfest-accepted

#66 issue #64 - Beautification of post module UI
  backend/uploads/2024-10-27T08-58-19.142Z-vaibhav saini1.jpg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/User/myPosts.js
  frontend/src/shared/components/AllPosts.js
  frontend/src/styles/post.module.css
  frontend/src/styles/posts.css
Labels: hacktoberfest-accepted
